### ISSUE TITLE
Won't startIf there is no internet connection

### ISSUE THREAD

**Issue by OtavioProfeta** [antunnitraj/OfflineMinecraftLauncher#1]
Hello, first of all, I would like to congratulate you for creating this wonderful launcher. But I went to test it on a Windows 10 system and the program only works properly if the computer is connected to the internet. Can this be modified to start without any connection?

**Comment by antunnitraj** [comment]
I'm happy that you like this launcher!

This was my first ever C# program and I'm still finding a way to cache the list of versions because making a minecraft launcher work completely offline is a tough task.

This launcher (currently) is for those who want to play with friends on offline servers (online-mode=false) and don't want to download the launcher that starts with a "T" that is owned by bad people.

Currently only [PrismLauncher](https://prismlauncher.org/) with my [bypass](https://github.com/antunnitraj/Prism-Launcher-PolyMC-Offline-Bypass) works truly offline.
